### ISSUE TITLE
CheckDate

### ISSUE THREAD

**Issue by jrgs** [Berekun/data_acces_dbi_2324#6]
https://github.com/Berekun/data_acces_dbi_2324/blob/c9d2975baedfe3dc649e2afd496b3f4b256d111f/Unit%201/Exercise%201/src/Exercise_4/MyDate.java#L42-L74

Se debería controlar la fecha en conjunto para evitar, por ejemplo, cambios de año de bisiesto a no bisiesto.

**Comment by Berekun** [comment]
Esto ya esta corregido
