### ISSUE TITLE
Return value

### ISSUE THREAD

**Issue by jrgs** [Berekun/data_acces_dbi_2324#8]
https://github.com/Berekun/data_acces_dbi_2324/blob/be1016021b7d367b630da5971a9627cb12256bfa/Unit%201/Exercise%201/src/Exercise_5/FormatImage.java#L41

No es buena idea hacer el System.out en las funciones, hay que devolver valores e imprimir en el programa principal

**Comment by Berekun** [comment]
ya esta corregido
