### ISSUE TITLE
Not valid

### ISSUE THREAD

**Issue by jrgs** [Berekun/data_acces_dbi_2324#9]
https://github.com/Berekun/data_acces_dbi_2324/blob/a459fa5fca9cd48e35fb44b91db4fad57c64223d/Unit%201/Exercise%201/src/Exercise_6/exercise_5_4_2.java#L19-L25

Esta solución no es válida, no saca ventaja del hecho de que los ficheros iniciales estén ordenados.

**Comment by Berekun** [comment]
ya esta
